import { Router } from 'express';
import healthRouter from './health';
import { requireAuth } from '../lib/supabase';
import { rateLimit } from '../lib/rate-limit';
import { accountRouter } from './account';
import { aiRouter } from './ai';
import { communityRouter } from './community';
import { careRouter } from './care';
import { nutritionistRouter } from './nutritionist';
import { campusRouter } from './campus';
const router = Router();
router.use(healthRouter);
router.use('/v1', requireAuth, rateLimit(120, 'user'));
router.use('/v1', accountRouter);
router.use('/v1/care', careRouter);
router.use('/v1/nutritionist', nutritionistRouter);
router.use('/v1/campus', campusRouter);
router.use('/v1/ai', rateLimit(10, 'user'), aiRouter);
router.use('/v1/community', rateLimit(60, 'user'), communityRouter);
export default router;
