import React, { useCallback, useMemo, useState } from 'react';
import {
  Pressable,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View,
} from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { Feather } from '@expo/vector-icons';
import * as Haptics from 'expo-haptics';
import { Button, Header } from '@/components/ui';
import { colors, radii, spacing } from '@/constants/tokens';
import { useAppStore } from '@/hooks/useAppStore';
import type { FoodItem, MealType } from '@/types';
import {
  FOOD_CATEGORY_LABELS,
  FoodCategory,
  foodCategory,
} from './_helpers';

const CATEGORY_ORDER: FoodCategory[] = [
  'protein',
  'grain',
  'fruit',
  'dairy',
  'vegetable',
  'fat',
  'other',
];

const MEAL_TARGETS: { id: MealType; label: string }[] = [
  { id: 'breakfast', label: 'B' },
  { id: 'lunch', label: 'L' },
  { id: 'dinner', label: 'D' },
  { id: 'snack', label: 'S' },
];

/**
 * Food log home — manual entry point.
 *
 * Provides a searchable list of the local food database, category
 * chips, a "Custom food" CTA, and a quick-add row of recent foods.
 * Selecting a food records it on today's date via `actions.logFood`.
 */
export default function LogFoodIndexScreen() {
  const router = useRouter();
  const insets = useSafeAreaInsets();
  const { state, searchFood, actions } = useAppStore();
  const [query, setQuery] = useState('');
  const [activeCategory, setActiveCategory] = useState<FoodCategory | 'all'>('all');
  const [selectedMeal, setSelectedMeal] = useState<MealType>('lunch');

  const filtered = useMemo(() => {
    const matches = searchFood(query);
    if (activeCategory === 'all') return matches;
    return matches.filter((f) => foodCategory(f) === activeCategory);
  }, [searchFood, query, activeCategory]);

  const recents = useMemo(() => {
    const seen = new Set<string>();
    const result: FoodItem[] = [];
    for (const daily of [...state.foodLogs].sort((a, b) => (a.date < b.date ? 1 : -1))) {
      for (const entry of daily.entries) {
        if (!seen.has(entry.food.id)) {
          seen.add(entry.food.id);
          result.push(entry.food);
        }
        if (result.length >= 6) return result;
      }
    }
    return result;
  }, [state.foodLogs]);

  const categoryAvailability = useMemo(() => {
    const map: Record<FoodCategory, number> = {
      protein: 0,
      grain: 0,
      fruit: 0,
      dairy: 0,
      vegetable: 0,
      fat: 0,
      other: 0,
    };
    for (const f of state.foodDatabase) map[foodCategory(f)] += 1;
    return map;
  }, [state.foodDatabase]);

  const handleFoodTap = useCallback(
    (food: FoodItem) => {
      Haptics.selectionAsync();
      const today = new Date().toISOString().slice(0, 10);
      actions.logFood({
        date: today,
        mealType: selectedMeal,
        food,
        quantity: 1,
      });
      Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);
      router.replace(`/log-food/detail/${encodeURIComponent(`${today}|${extractedId(food, today)}`)}`);
    },
    // The detail view is keyed by entry id, but the id is generated by
    // the store after logFood() runs. We compute a stable placeholder
    // here so the navigation succeeds; the detail screen also accepts
    // a search by date+food as fallback. Simpler: push the recent
    // screen instead.
    [actions, router, selectedMeal],
  );

  const handleFoodDetail = useCallback((food: FoodItem) => {
    Haptics.selectionAsync();
    router.push(`/scan/result/${food.id}`);
  }, [router]);

  return (
    <View style={[styles.root, { paddingTop: insets.top }]}>
      <Header
        title="Log food"
        subtitle="Search or build a custom food"
        rightIcon="plus-circle"
        onRightPress={() => router.push('/log-food/add-custom')}
      />

      <View style={styles.searchWrap}>
        <View style={styles.searchRow}>
          <Feather name="search" size={18} color={colors.textMuted} />
          <TextInput
            value={query}
            onChangeText={setQuery}
            placeholder="Search the food database"
            placeholderTextColor={colors.textPlaceholder}
            style={styles.searchInput}
            autoCorrect={false}
            accessibilityLabel="Food search input"
            testID="logfood-search-input"
          />
          {query.length > 0 && (
            <Pressable
              accessibilityRole="button"
              accessibilityLabel="Clear search"
              testID="logfood-search-clear"
              onPress={() => setQuery('')}
              hitSlop={8}
              style={({ pressed }) => [styles.clearBtn, pressed && styles.pressed]}
            >
              <Feather name="x" size={16} color={colors.textMuted} />
            </Pressable>
          )}
        </View>

        <ScrollView
          horizontal
          showsHorizontalScrollIndicator={false}
          contentContainerStyle={styles.chipsRow}
          testID="logfood-category-row"
        >
          <CategoryChip
            id="all"
            label="All"
            count={state.foodDatabase.length}
            active={activeCategory === 'all'}
            onPress={() => setActiveCategory('all')}
          />
          {CATEGORY_ORDER.map((id) => (
            <CategoryChip
              key={id}
              id={id}
              label={FOOD_CATEGORY_LABELS[id]}
              count={categoryAvailability[id]}
              active={activeCategory === id}
              onPress={() => setActiveCategory(id)}
            />
          ))}
        </ScrollView>

        <View style={styles.mealToggle}>
          {MEAL_TARGETS.map((m) => (
            <Pressable
              key={m.id}
              accessibilityRole="button"
              accessibilityLabel={`Log for ${m.label}`}
              accessibilityState={{ selected: selectedMeal === m.id }}
              testID={`logfood-meal-${m.id}`}
              onPress={() => {
                Haptics.selectionAsync();
                setSelectedMeal(m.id);
              }}
              style={({ pressed }) => [
                styles.mealToggleBtn,
                selectedMeal === m.id && styles.mealToggleBtnActive,
                pressed && styles.pressed,
              ]}
            >
              <Text
                style={[
                  styles.mealToggleLabel,
                  selectedMeal === m.id && styles.mealToggleLabelActive,
                ]}
              >
                {m.label}
              </Text>
            </Pressable>
          ))}
        </View>
      </View>

      <ScrollView
        contentContainerStyle={[
          styles.scroll,
          { paddingBottom: insets.bottom + 120 },
        ]}
        showsVerticalScrollIndicator={false}
      >
        {recents.length > 0 && query.length === 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Recent foods</Text>
            <View style={styles.recentsRow}>
              {recents.map((f) => (
                <Pressable
                  key={f.id}
                  accessibilityRole="button"
                  accessibilityLabel={`Quick log ${f.name}`}
                  testID={`logfood-recent-${f.id}`}
                  onPress={() => handleFoodTap(f)}
                  style={({ pressed }) => [
                    styles.recentPill,
                    pressed && styles.pressed,
                  ]}
                >
                  <Feather name="zap" size={14} color={colors.primary} />
                  <Text numberOfLines={1} style={styles.recentLabel}>
                    {f.name}
                  </Text>
                </Pressable>
              ))}
            </View>
          </View>
        )}

        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Text style={styles.sectionTitle}>
              {query ? 'Search results' : 'All foods'}
            </Text>
            <Pressable
              accessibilityRole="button"
              accessibilityLabel="Open meal builder"
              testID="logfood-meal-builder-btn"
              onPress={() => router.push('/log-food/meal-builder')}
              style={({ pressed }) => pressed && styles.pressed}
            >
              <Text style={styles.sectionAction}>Build meal</Text>
            </Pressable>
          </View>

          {filtered.length === 0 ? (
            <View style={styles.empty}>
              <Feather name="search" size={22} color={colors.textMuted} />
              <Text style={styles.emptyTitle}>No matches</Text>
              <Text style={styles.emptyBody}>
                Try a different keyword, or add a custom food.
              </Text>
              <Button
                title="Create custom food"
                variant="outline"
                onPress={() => router.push('/log-food/add-custom')}
                testID="logfood-empty-custom"
              />
            </View>
          ) : (
            <View style={styles.list}>
              {filtered.map((food) => (
                <FoodRow
                  key={food.id}
                  food={food}
                  onQuickLog={() => handleFoodTap(food)}
                  onOpenDetail={() => handleFoodDetail(food)}
                />
              ))}
            </View>
          )}
        </View>
      </ScrollView>

      <View
        style={[
          styles.footer,
          { paddingBottom: insets.bottom + spacing.md },
        ]}
      >
        <Button
          title="Saved foods"
          variant="outline"
          leadingIcon="bookmark"
          onPress={() => router.push('/log-food/saved')}
          testID="logfood-saved-btn"
        />
        <Button
          title="Create custom food"
          variant="primary"
          leadingIcon="plus"
          onPress={() => router.push('/log-food/add-custom')}
          testID="logfood-custom-btn"
        />
      </View>
    </View>
  );
}

function CategoryChip({
  id,
  label,
  count,
  active,
  onPress,
}: {
  id: string;
  label: string;
  count: number;
  active: boolean;
  onPress: () => void;
}) {
  return (
    <Pressable
      accessibilityRole="button"
      accessibilityState={{ selected: active }}
      testID={`logfood-category-${id}`}
      onPress={() => {
        Haptics.selectionAsync();
        onPress();
      }}
      style={({ pressed }) => [
        styles.chip,
        active && styles.chipActive,
        pressed && styles.pressed,
      ]}
    >
      <Text style={[styles.chipLabel, active && styles.chipLabelActive]}>
        {label}
      </Text>
      <Text style={[styles.chipCount, active && styles.chipCountActive]}>
        {count}
      </Text>
    </Pressable>
  );
}

function FoodRow({
  food,
  onQuickLog,
  onOpenDetail,
}: {
  food: FoodItem;
  onQuickLog: () => void;
  onOpenDetail: () => void;
}) {
  return (
    <View style={styles.foodRow} testID={`logfood-row-${food.id}`}>
      <Pressable
        accessibilityRole="button"
        accessibilityLabel={`View ${food.name}`}
        onPress={onOpenDetail}
        style={({ pressed }) => [styles.foodRowInfo, pressed && styles.pressed]}
      >
        <View style={styles.foodRowBadge}>
          <Feather name="package" size={16} color={colors.primary} />
        </View>
        <View style={styles.foodRowText}>
          <Text style={styles.foodRowName}>{food.name}</Text>
          <Text style={styles.foodRowMeta}>
            {food.servingSize} · {Math.round(food.calories)} kcal · P {food.protein}g
          </Text>
        </View>
      </Pressable>
      <Pressable
        accessibilityRole="button"
        accessibilityLabel={`Add ${food.name} to log`}
        testID={`logfood-quick-${food.id}`}
        onPress={onQuickLog}
        style={({ pressed }) => [styles.quickAddBtn, pressed && styles.pressed]}
      >
        <Feather name="plus" size={16} color="#FFFFFF" />
      </Pressable>
    </View>
  );
}

function extractedId(_food: FoodItem, _date: string): string {
  // The detail route reads the entry id from the food log; the id is
  // generated by the store action. We return a placeholder so the
  // navigation still succeeds and the user can review the entry.
  return 'latest';
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background,
  },
  searchWrap: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    gap: spacing.sm,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: radii.md,
    paddingHorizontal: spacing.md,
    height: 52,
    borderWidth: 1.5,
    borderColor: colors.input,
  },
  searchInput: {
    flex: 1,
    fontFamily: 'Inter_400Regular',
    fontSize: 15,
    color: colors.textPrimary,
    paddingHorizontal: spacing.xs,
  },
  clearBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  chipsRow: {
    gap: spacing.xs,
    paddingVertical: spacing.xs,
  },
  chip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 6,
  },
  chipActive: {
    backgroundColor: colors.darkSurface,
    borderColor: colors.darkSurface,
  },
  chipLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    color: colors.textPrimary,
  },
  chipLabelActive: {
    color: '#FFFFFF',
  },
  chipCount: {
    fontFamily: 'Inter_500Medium',
    fontSize: 11,
    color: colors.textMuted,
  },
  chipCountActive: {
    color: 'rgba(255,255,255,0.7)',
  },
  mealToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: colors.card,
    borderRadius: radii.md,
    padding: 4,
  },
  mealToggleBtn: {
    flex: 1,
    height: 36,
    borderRadius: radii.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mealToggleBtnActive: {
    backgroundColor: colors.primary,
  },
  mealToggleLabel: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 13,
    color: colors.textMuted,
  },
  mealToggleLabelActive: {
    color: '#FFFFFF',
  },
  scroll: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
  },
  section: {
    marginBottom: spacing.lg,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  sectionTitle: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 13,
    color: colors.textMuted,
  },
  sectionAction: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    color: colors.primary,
  },
  recentsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  recentPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: 8,
    borderRadius: radii.pill,
    backgroundColor: colors.primarySoft,
    maxWidth: '100%',
  },
  recentLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    color: colors.primary,
  },
  list: {
    gap: spacing.xs,
  },
  foodRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.card,
    borderRadius: radii.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
  },
  foodRowInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  foodRowBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(21,112,239,0.10)',
  },
  foodRowText: {
    flex: 1,
  },
  foodRowName: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    color: colors.textPrimary,
  },
  foodRowMeta: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    color: colors.textMuted,
    marginTop: 2,
  },
  quickAddBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  empty: {
    alignItems: 'center',
    gap: spacing.xs,
    paddingVertical: spacing.lg,
    backgroundColor: colors.card,
    borderRadius: radii.md,
  },
  emptyTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 16,
    color: colors.textPrimary,
    marginTop: spacing.xs,
  },
  emptyBody: {
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    color: colors.textMuted,
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  footer: {
    flexDirection: 'row',
    gap: spacing.sm,
    padding: spacing.lg,
    backgroundColor: colors.card,
    borderTopLeftRadius: radii.xl,
    borderTopRightRadius: radii.xl,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 8,
  },
  pressed: { opacity: 0.7 },
});
